services:
    nodepay:
        container_name: Nodepay
        build:
            context: ./nodepay_src
        restart: unless-stopped
        volumes:
            # Relative volume: Maps the './nodepay_config' to get .env updated file
            - ./nodepay_config:/app/config
        networks:
            default:
                ipv4_address: 172.106.0.70 # Example static IP

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.106.0.0/16 # Example subnet